import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/globals.css'
import { cn } from "@/lib/utils"
import PageHeader from "@/components/page-header";
import { Sidebar } from "@/components/sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ReactQueryProvider } from "./providers";
import { ThemeProvider } from "@/components/theme-provider";
 
const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ReactQueryProvider>
                <div
                  className={cn(
                    "min-h-screen overflow-hidden bg-background font-sans antialiased flex start-0 justify-start",
                    fontSans.variable
                  )}
                >

                  <ScrollArea className="w-72 max-h-screen overflow-y-auto scrollbar-none shadow-sm border-r">

                    <Sidebar />
                  </ScrollArea>
                  <ScrollArea className="flex-1 max-h-screen overflow-y-auto py-4">
                    <PageHeader/>
                    
                  <div className="px-6">{props.children}</div>

                  {
                    props.modal
                  }
                  <div id="modal-root"/>
                  </ScrollArea>

                </div>
                  
                
                
            </ReactQueryProvider>
          </ThemeProvider>
        </body>
    </html>
  )
}
